# InputTip: url=path
[Files]
src/i18n/zh-CN.ahk=i18n/zh-CN.ahk
src/i18n/en-US.ahk=i18n/en-US.ahk
src/core/about.ahk=core/about.ahk
src/core/config.ahk=core/config.ahk
src/core/core.ahk=core/core.ahk
src/core/cursor.ahk=core/cursor.ahk
src/core/gui.ahk=core/gui.ahk
src/core/i18n.ahk=core/i18n.ahk
src/core/ime.ahk=core/ime.ahk
src/core/ini.ahk=core/ini.ahk
src/core/init.ahk=core/init.ahk
src/core/input-method.ahk=core/input-method.ahk
src/core/jab.ahk=core/jab.ahk
src/core/manifest.ahk=core/manifest.ahk
src/core/more-settings.ahk=core/more-settings.ahk
src/core/overlay.ahk=core/overlay.ahk
src/core/runtime.ahk=core/runtime.ahk
src/core/startup.ahk=core/startup.ahk
src/core/symbol.ahk=core/symbol.ahk
src/core/tray-menu.ahk=core/tray-menu.ahk
src/core/ui.ahk=core/ui.ahk
src/core/utils.ahk=core/utils.ahk
src/core/var.ahk=core/var.ahk
src/CHANGELOG.md=CHANGELOG.md
src/InputTip.ahk=InputTip.ahk
src/InputTip.JAB.JetBrains.ahk=InputTip.JAB.JetBrains.ahk
src/InputTip.updater.ahk=InputTip.updater.ahk
.gitignore=../.gitignore
InputTip.bat=../InputTip.bat
README.md=../README.md
LICENSE=../LICENSE
src/version.txt=version.txt
src/version-zip.txt=version-zip.txt
