name: Publish winget-pkgs on release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  create-pr-branch:
    runs-on: windows-latest
    steps:
      - name: Checkout InputTip
        uses: actions/checkout@v4
        with:
          repository: abgox/InputTip
          path: InputTip

      - name: Configure Git
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "abgox"
          git config --global user.email "abgohxf@outlook.com"
          # 使用 HTTPS + Token 认证
          git config --global url."https://$env:GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"

      - name: Clone from GitHub and Create PR branch
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $temp_dir = "temp_$(Get-Date -Format 'yyyyMMddHHmmss')"
          git clone --depth 1 "https://github.com/abgox/winget-pkgs.git" $temp_dir
          cd $temp_dir
          $info = ..\InputTip\scripts\create-winget-manifest.ps1 "manifests\a\abgox\InputTip"
          $new_branch = $info.new_branch
          git checkout -b $new_branch
          git add .
          git commit -m $info.commit_msg
          git push origin $new_branch
