name: Publish winget-pkgs on release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  create-pr-branch:
    runs-on: windows-latest
    env:
      REPO: ${{ github.repository }}
      USER_NAME: "abgox"
      USER_EMAIL: "abgohxf@outlook.com"
    steps:
      - name: Configure Git
        shell: pwsh
        run: |
          git config --global user.name $env:USER_NAME
          git config --global user.email $env:USER_EMAIL

      - name: Clone from GitHub and Create PR branch
        shell: pwsh
        run: |
          git clone --depth 1 https://${{ secrets.PAT_TOKEN }}@github.com/abgox/InputTip.git InputTip
          git clone --depth 1 https://${{ secrets.PAT_TOKEN }}@github.com/abgox/winget-pkgs.git winget-pkgs
          cd winget-pkgs
          $info = ..\InputTip\scripts\create-winget-manifest.ps1 "manifests\a\abgox\InputTip"
          $new_branch = $info.new_branch
          git checkout -b $new_branch
          git add .
          git commit -m $info.commit_msg
          git push origin $new_branch
